export const projects = [
  {
    id: '1',
    screenshot: '/dev-overflow.png',
    title: 'dev overflow',
    subTitle: 'Stack overflow clone',
    stack: [
      'next.js',
      'typescript',
      'clerck',
      'tailwindcss',
      'mongodb',
      'mongoose',
      'clerck webhooks',
    ],
    description: `Dev-Overflow is a modern Stack Overflow clone designed for developers to share knowledge and solve problems collaboratively. Built with Next.js, TypeScript, and Tailwind CSS, it offers a seamless user experience with features like creating and answering questions, interactive likes, and commenting. The platform includes a scoring system to reward engagement and a rich 'What You See Is What You Get' (WYSIWYG) editor for writing detailed questions and answers with code snippets. Authentication and authorization are powered by Clerk, ensuring secure and personalized user interactions.`,
    date: 'Dec 5, 2024',
    github: 'https://github.com/adel-gu/dev-overflow',
    live: 'https://dev-overflow-adels-projects-d623dcad.vercel.app/',
    color: 'rgba(249,115,22)',
    btnBg: 'rgba(154,52,18,0.5)',
    btnBgHover: 'rgba(67,20,7)',
    cardBg: 'rgba(154,52,18,0.05)',
  },
  {
    id: '2',
    screenshot: '/meta-market.png',
    title: 'Meta Market',
    subTitle: 'NFT marketplace UI website',
    stack: [
      'react',
      'typescript',
      'tailwindcss',
      'nx',
      'rollup',
      'Module Federation',
      'vitest',
      'playwright',
      'storybook',
      'svgr',
      'lint-staged',
      'husky',
      'ci/cd',
      'aws',
    ],
    description:
      'Meta Market is a NFT marketplace built using a monorepo architecture, leveraging React and microfrontend design principles. The application is divided into five independent React applications, each serving a distinct function within the ecosystem, along with shared design system and icons packages. This microfrontend architecture ensures modularity, scalability, and independent deployment, while the monorepo setup allows for seamless code sharing and consistency across all projects.',
    date: 'Nov 19, 2024',
    github: 'https://github.com/adel-gu/meta-market/tree/main',
    live: 'https://d1zer73e5vmia3.cloudfront.net/',
    color: 'rgba(139,92,246)',
    btnBg: 'rgba(91,33,182,0.5)',
    btnBgHover: 'rgba(46,16,101)',
    cardBg: 'rgba(91,33,182,0.05)',
  },
  {
    id: '3',
    screenshot: '/room-manager.png',
    title: 'Room Manager',
    subTitle: 'Room management and reservations app',
    stack: [
      'react',
      'typescript',
      'tanstack',
      'styled component',
      'node',
      "api's",
      'express',
      'mongodb',
      'mongoose',
      'JWT',
      'cloudinary',
    ],
    description:
      'Room Manager is a comprehensive room management and reservation platform designed to streamline operations for administrators and guests alike. The application allows users to browse available rooms, register visitors and guests, and manage multiple admin accounts with role-based permissions. Authentication and authorization were custom-built using JSON Web Tokens (JWT) for a secure and tailored experience. Cloudinary powers image upload and optimization, ensuring fast and high-quality visuals.',
    date: 'Sep 2, 2024',
    github: 'https://github.com/adel-gu/room-management',
    live: 'https://room-management-giky.onrender.com/',
    color: 'rgba(79,70,229)',
    btnBg: 'rgba(55,48,163,0.5)',
    btnBgHover: 'rgba(30,27,75)',
    cardBg: 'rgba(55,48,163,0.05)',
  },
  {
    id: '4',
    screenshot: '/fintechracy.png',
    title: 'Fintechracy',
    subTitle: 'Fintechracy official website',
    stack: ['react', 'tailwindcss', 'framer motion', 'shadcn'],
    description: `Fintechracy is on a mission to eliminate paper receipts by providing innovative software solutions. After two unsuccessful attempts to develop a professional website, I stepped in to deliver a final version that met the company's vision and market standards. The website, built with React, Tailwind CSS, ShadCN, and Framer Motion, features smooth animations, complete responsiveness, and multi-language support for a seamless global user experience.`,
    date: 'Jan 2, 2024',
    github: '',
    live: 'https://www.fintechracy.org/',
    color: 'rgba(34,197,94)',
    btnBg: 'rgba(22,101,52,0.5)',
    btnBgHover: 'rgba(5,46,22)',
    cardBg: 'rgba(22,101,52,0.05)',
  },
  {
    id: '5',
    screenshot: '/chatbotify.png',
    title: 'ChatBotify Gallery',
    subTitle: 'ChatBotify Gallery website',
    stack: ['react', 'tailwindcss', 'figma'],
    description: `Chatbotify Gallery is an (open-source) project showcasing customizable chatbot designs. When I joined the team, one major blocker was the lack of a unified color palette and design system. I addressed this by creating a cohesive palette that aligned with the application's style and feel, streamlining the design process for the entire team. My contributions include designing and developing the About page using React and Tailwind CSS, as well as working on the Theme Builder page—a feature enabling users to customize chatbots to match their tone and branding.`,
    date: 'Jan 2, 2024',
    github: 'https://github.com/adel-gu/react-chatbotify-gallery-website',
    live: 'https://gallery.react-chatbotify.com/',
    color: 'rgba(6,182,212)',
    btnBg: 'rgba(7,89,133,0.5)',
    btnBgHover: 'rgba(8,47,73)',
    cardBg: 'rgba(7,89,133,0.05)',
  },
];
